export const POPS=[
	{
		id:1,
		target:'Popover1',
		title:'Cart',
		img:'assets/img/emptycart.png'
	},
	{
		id:2,
		target:'Popover2',
		title:'Notification',
		img:'assets/img/no_notification.png'
	},
	{
		id:3,
		target:'Popover3',
		title:'Chat',
		img:'assets/img/chat.svg'
	}
];