
export const ADS_LOADING = 'ADS_LOADING';
export const ADS_FAILED = 'ADS_FAILED';
export const ADD_ADS = 'ADD_ADS';

export const HIGHLIGHTS_LOADING = 'HIGHLIGHTS_LOADING';
export const HIGHLIGHTS_FAILED = 'HIGHLIGHTS_FAILED';
export const ADD_HIGHLIGHTS = 'ADD_HIGHLIGHTS';


export const CATEGORIES_LOADING = 'CATEGORIESS_LOADING';
export const CATEGORIES_FAILED = 'CATEGORIES_FAILED';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';

export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';


export const SHOPS_LOADING = 'SHOPS_LOADING';
export const SHOPS_FAILED = 'SHOPS_FAILED';
export const ADD_SHOPS = 'ADD_SHOPS';

export const ALLSHOPS_LOADING = 'ALLSHOPS_LOADING';
export const ALLSHOPS_FAILED = 'ALLSHOPS_FAILED';
export const ADD_ALLSHOPS = 'ADD_ALLSHOPS';

